dna = "GACATGTGTGGACCTCTCATATGCGTATCTCCATCCTTGCGGCTGCGGTTTAATGGAGCAGAACGACGATCGAGCAGTCCACCGGTTATCTGCACGGGCTCATCGCATGGCTCTAGAGGTTAGGTGGTACCTGGTACACTATTGAGGTGGGTTAAATCTATATGTGACGTGCGCCTATTTGTAGTTCGCGTGAGATAGGCTATGTAGCCTTGGCATGCTGCAGAGCAGTCACTAGATATTCCACGCAATGCACTCCGACCCGCGCATGTTAGGGGTATTCAAAGTGCTAGTCGACAGCGTACTACATACACAACCATGTCAATGAGAGTATTTCGCTATCACTTAAGAGGCCTCGTACGAACACAAAGTGATTCCAATAGCGGCTATCGTCTCGCCGTTTGGTACTTCAGACCGTCTCGAACAGAGCATCGTACGCGTACCGCCTTAGCCGGGTCCTGGTCTAAATCCATTTCGGAACTCACTGAAACGAATCCCACGCTCGAGATTACCAGACCCCCCTATTAAGGTTAAAAGTAGAGAGGAGGGAGGATCCCCGAATCATGGGGTGGGAACACATTTCAATGGAAGCACTAATTTCGGTCACCCCTGACCAGGCTAAAATTACTAGTTATCTATTACCATGGTGTATGCTTGTACGTCCAATACGCAACGATAGCTTCTATACATCCCACCAGCCTGGGCGAACTAGCCTTTACGCACTTAAAGTTGTAAGAATGATATTAAGTGGGGACATTGCCCTGCCGTGCCGCTCAAACAGAGACTTGCTGGGGTCCCACGAAACCCCTAAAGCCATACGCGTAGATCGATGTACTTTTCGCAGCGATGCCATAGCACGCCCAGTGGGGACGAACTAACCAAAGATAGACCCCCTTAACAGCGCGGAAATCCGAATTTTCTGGTTAAGTGAA"

def contagem(dna: str):
    #A', 'C', 'G', and 'T')
    a = 0
    c = 0
    g = 0
    t = 0

    for i in dna: 
        if i == "A":
            a += 1

        elif i == "C":
            c += 1

        elif i == "G":
            g += 1

        elif i == "T":
            t += 1
        else: 
            pass
    return print(f"{a} {c} {g} {t}")

contagem(dna)
