dna = "TAGATCTTGCCTGCAAGGCTCAGTTAATGCCATTAGAGTAGGCAATGCTAATTTTGTACTGAGACCATGGCGCCCGTTAAGTGAATACTGCGCGGTATTCATATTATTTGCTGCTCTTCTATGATACTCCTGTTAAGTGCGTACTTCCTGTGTCACTTCGGATAGTGTTTAGCTAGGGCGATCCGTCGTCTTGCTTTAGAGAAAGAGCCTATCAGTAGGAGATCTTAAAGTGTTAGTCTGACCGACACGGCATTGGCATAGGTGTTGTTGTATCCCTAATGGGCCTGGGTCTTTGGATGCATAAGATGGACTGGCCGACAATTAGGGTATGCTTTTCTGATCGACACACTGTTAATCCGTATGCGGGCGGAGCATAGCTTTGTTATAAATTGGGTGCACTTGCTAGTGTTTAAGCCAAGCTTGACAGGATTGTTTCACGCTGAACGCCACCAGGTGATGCCCAGAAGAAGTTCAGTCTGACCGGTACGATATGGCTCGTGCAGTTATGAGCAACACCTCTTCGGACTTTATGGGAGGAAGTTTGAGGATTGTCGGAGGGGGGGCGTCAAAAACCCTTGAAGCCCGGACGTTTGCAGCCGCGGAGCAAGTTTGACGACTGCCCTTCCGGCCTAGAGCAGACCCAAACTAAAGAGCAAATTTTTATAACAGAAATTCAGGATAGAGGAGCACAACCGCATTCGGCACTCATTTGTACGAGAGGAGTATGGAGCTAGGGAGTGTTCTCGCCTAGAGGCATATAAATATAAATATAGCAGTCCCCATGGACTCAACGGTCTACCCGGACAATAAAACGTGTAAGCTGCCATGGTAAGTGGCGCCTTTCCGCTGAGTGACCTATACTCAGGAGACACGGGCGAGGCATTATCATAAATGTTAACAACGTTTAGTAGATGAGATAATACGACCGCCGGCCCCCCCGCACTCCGGAAGAATCGTAGAGCGCTACCTCCCTGTCGACCGGGAAGCTGGTCGATGGACG"

def transcricao(dna:str):
    rna_temp = []

    for i in dna: 
        if i == "U":
            i = "T"
        else:
            pass
        rna_temp.append(i)
    
    rna = "".join(rna_temp)

    return print(rna)

transcricao(dna)

