#IN AAAACCCGGT
#   TTTTGGGCCA
#OUT ACCGGGTTTT

helice = "ATATGCCCTCGTAAGTGAAACCTTAATTTCACTCGCCCGTCTACGTTGCCATTCGGTTCCTCAGGCGTGTTGACGGTTGCGACGCCGGGTAAGAAAAGTGCAGGTGTGGTGGTTTTTTACTATCGGGGCGATCGTCCCGGACAGGGCTACACCCAAATATATGGCGCGGCGCTAGGGTTTGGGCATTATGTGCACAAAGGTACCCGATCAACATAGTTATATAACGTTATAAAAACTTTCCGGAGATCGTAAACTTATTGGGGAGTAAAAAGATTTTTACAAGGTACATCCGGGACGTTACCAAATAGTCCGAAGATGGCATGGACTGATGTTGCTCCAAGGTCCAATCCAATTTGACGCTAGACGGGGCAGACTATCCCCCACCTCTACCCTCCCCTGGACCCGTAACACTAAGATATGAGCCTAACCACAACCGTATCTACTGAGATCGGCTCCCGTGGTAGGCACTCCGGGGCCCAGTATAGGAAGAAAGTTTGCACAGAGTCAAACTGGTATCGTTACGGTGTTCAGCTTAAGTTTCCCGTCGCCATAGGGACACACGCCCCCTTGAGTGAGATTAGGGGCTGCACTTAGGGACACACCGGAGAGAAGGCAACGTAGTCCTTTACCAAGTTGTCCTCCATAAGTTGTGTGATCCCACACCAAACACAACTAGTCCCCGTTGGACTCAACCTGGCTAATTGAGTCTTAGACATGTCTTTGGGTACGCTTCGCCAACAGATTGTCGCCTGGCAATTTTTTGCTTCTTAAAGGTTTCGCAGCTTCTTAAAAGGGTACATTTGCCTGTACCCTGAGTCGCGTAACCCTGGCTACCCACTCTTCACGAGATATTCTGCGGCAACGGCAGGTCCGGGCTTCACGGATAATCCTACATATACCTGCAGACGAAACCGTAGCCATC" 

def complemento(helice:str):
    
    bases = {
        "A":"T",
        "T":"A",
        "G":"C",
        "C":"G"
    }

    helice_temp =[]

    for i in helice:
        letra = bases[i]
        helice_temp.append(letra)

    helice_temp = helice_temp[::-1]

    segunda_helice = "".join(helice_temp)

    return print(segunda_helice)

complemento(helice)



